### ISSUE TITLE
Mathnote logo contribution

### ISSUE THREAD

**Issue by psikoz** [limitedeternity/MathNote#1]
Hey @limitedeternity.  I have researched the application a bit and i wanted to logo designing for it.

I was inspired by the initials of the app. M and N.

I compatible the letter N with mathematics. (By using pi instead of n)

Also, I used the color compatible with the backgrounds in the readme file. WDYT about the logo?

![mathnote](https://user-images.githubusercontent.com/40601249/42943897-cf88109c-8b6c-11e8-9fb5-015f4053559e.jpg)

**Comment by limitedeternity** [comment]
Awesome! I love how third icon looks, but background width on it seems a bit large, don't you think?

**Comment by psikoz** [comment]
I am glad you like it. :) Actually, it represents the background. Example; it will look like this:

![1](https://user-images.githubusercontent.com/40601249/43003562-944b06dc-8c35-11e8-8cab-43a7064081ea.png)

**Comment by limitedeternity** [comment]
Have you already integrated this one into the application header?

**Comment by psikoz** [comment]
I did not integrate it :) If you want it, I will send you a pr for these 3 versions. Which one do you prefer?

**Comment by limitedeternity** [comment]
That's cool! I'd like to see how that last two icons will look like

**Comment by psikoz** [comment]
here you are;

![1](https://user-images.githubusercontent.com/40601249/43004164-9da39274-8c37-11e8-949b-04a974c180d8.png)
![2](https://user-images.githubusercontent.com/40601249/43004165-9e2ffd54-8c37-11e8-8ebc-121b5b1c38de.png)

**Comment by limitedeternity** [comment]
Last one is awesome! I'd like to see your PR with this icon integrated.

**Comment by psikoz** [comment]
okay, i will send a pr. 
Would you give me information about this font name? Because, I will include all variations and send you a pr. 
![4](https://user-images.githubusercontent.com/40601249/43004542-cd95d400-8c38-11e8-9bca-4d5669c47653.png)

**Comment by limitedeternity** [comment]
AFAIK this is Roboto, but there are other fonts (specified in CSS) that look like this one:

![screenshot from 2018-07-20 16-26-21](https://user-images.githubusercontent.com/24318966/43004927-e297f008-8c39-11e8-92f6-5e06737c7287.png)

**Comment by psikoz** [comment]
I'll send you all the variations with the roboto font.

**Comment by limitedeternity** [comment]
K, thanks

**Comment by limitedeternity** [comment]
Successfully merged and released! Great work, @psikoz. That's awesome!
